### ISSUE TITLE
Add support for ON CONFLICT clause to support upserts

### ISSUE THREAD

**Issue by apurvis** [diogob/postgres-copy#47]
I was poking around this gem but ultimately was unable to use it because I need to do some upserting, which is a newish feature as of postgres 9.5.

https://www.postgresql.org/docs/current/static/sql-insert.html#SQL-ON-CONFLICT

It's definitely a bit tricky to implement - any `copy_from` would need to know the indices that could conflict and then how to update the rows with `DO UPDATE SET` - but it would be a great feature to have.

In my solution I ultimately had to resort to this methodology:
```ruby
csv_data = CSV.parse(csv_string, headers: true)
csv_file = Tempfile.new([client.name, '_client_data', 'csv'])
tmp_table_name = "tmp_#{table_name}"

ActiveRecord::Base.connection.execute("
  CREATE TEMP TABLE #{tmp_table_name} AS SELECT * FROM #{table_name} WITH NO DATA;
  COPY #{tmp_table_name} (#{csv_data.headers.join(',')}) FROM '#{csv_file.path}' CSV HEADER;

  INSERT INTO #{table_name}
    SELECT *
    FROM #{tmp_table_name}
    ON CONFLICT (#{unique_key_columns.join(',')})
    DO UPDATE SET
      (updated_at, #{cols_to_update.join(',')}) =
      (NOW(), #{cols_to_update.map { |c| "EXCLUDED.#{c}" }.join(',')});

  DISCARD TEMP;
")
```

**Comment by diogob** [comment]
@apurvis your approach is perfectly fine. The only purpose of this gem is to provide some support for the COPY commands since it has historically poor ActiveRecord support. I believe that dealing with INSERT/UPSERT and any sort of conflict resolution falls out of the scope. Although I can see how another gem could be built on top of this one for that purpose ;)
